name: Organization Coding Hours Report

on:
  workflow_dispatch:
    inputs:
      repos:
        description: "Space-separated list of repositories (owner/name format)"
        required: true
      window_start:
        description: "Optional start date (YYYY-MM-DD)"
        required: false

permissions:
  contents: write   # required for pushing to the metrics branch
  # pages: write    # (only if publishing a site in a separate job)

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Org Coding Hours Action
        uses: LabVIEW-Community-CI-CD/org-coding-hours-action@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repos: ${{ github.event.inputs.repos }}
          window_start: ${{ github.event.inputs.window_start }}
          # metrics_branch: metrics    # (optional) enable branch push for JSON

      - name: Upload JSON reports
        uses: actions/upload-artifact@v4
        with:
          name: coding-hours-json
          path: reports/
